apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  type: LoadBalancer
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 5000        # This is the target port your container listens on.
      targetPort: 5000  # Container port.

